name: Claims Prediction CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.12
          poetry-version: 1.2.2

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Format code with Black
        run: poetry run black

      - name: Run pytest
        run: poetry run pytest

      - name: Check for linting errors
        run: |
          # Optionally, you can add linting or other static analysis steps here
          # Example: flake8 .
