name: "Production deployment"

concurrency: 1

#on:
#  push:
#   branches:
#     - main

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy -t production
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: production

  