name: "Staging deployment & test"

concurrency: 1

#on:
#  pull_request:
#    types:
#      - opened
#      - synchronize
#    branches:
#      - main

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy -t staging
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging

  run_pipeline:
    name: "Run pipeline"
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle run -t staging training-pipeline
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging

  run_integration_test:
    name: "Run integration test"
    runs-on: ubuntu-latest
    needs:
      - run_pipeline
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle run -t staging integration-test
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: staging